training_pipeline_config:
  pipeline_name: rental_bike_demand
  artifact_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/sumeet0701/Rental-Bike-Share-prediction/blob/main/Rental%20bike%20demand%20data.zip
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test

data_validation_config: 
  schema_dir: config
  schema_file_name:  schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  feature_enginneering_dir: feat_eng.pkl
  preprocessing_object_file_name: preprocessed.pkl

model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl

  
